[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  YARN_VERSION = "1.15.2"
  HUGO_VERSION = "0.55.3"

[context.production.environment]
  HUGO_ENV = "production"
  NODE_ENV = "production"

[context.deploy-preview]
  command = "yarn build-preview"
