backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

site_url: https://pine-maastricht.nl

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{day}}-{{month}}-{{year}}"
    preview_path: "post/{{slug}}"
    filter: {field: "ispost", value: "true"}
    fields: # The fields each document in this collection have
      - {label: "Is Post?", name: "ispost", widget: "hidden", default: "true"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Introduction", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "project"
    label: "Projects"
    folder: "site/content/project"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    filter: {field: "isproject", value: "true"}
    fields:
      - {label: "Is Project?", name: "isproject", widget: "hidden", default: "true"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Published", name: "publishdate", widget: "datetime"}
      - {label: "Last Updated", name: "lastmod", widget: "datetime"}
      - {label: "Introduction", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    preview_path: "{{slug}}"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - label: "Intro"
            name: intro
            widget: object
            fields:
              - {label: "Heading", name: "heading", widget: string}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Image", name: "image", widget: "image"}
      - file: "site/content/post/_index.md"
        label: "List of Posts"
        name: "posts"
        fields:
          - {label: "Menu", name: "menu", widget: "hidden", default: "{main: {weight: -80}}"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Description, name: description, widget: string}
      - file: "site/content/project/_index.md"
        label: "List of Projects"
        name: "projects"
        fields:
          - {label: "Menu", name: "menu", widget: "hidden", default: "{main: {weight: -90}}"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Description, name: description, widget: string}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Menu", name: "menu", widget: "hidden", default: "{main: {weight: -70}}"}
          - {label: "Link Title", name: linktitle, widget: hidden, default: "About"}
          - {label: "Title", name: title, widget: string}
          - {label: "Image", name: image, widget: image}
          - {label: "Description", name: description, widget: string}
          - label: "Introduction"
            name: intro
            widget: object
            fields:
              - {label: "Heading", name: "heading", widget: string}
              - {label: "Text", name: "text", widget: text}
          - label: "PINE Work"
            name: work
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: string}
              - label: Pillars
                name: columns
                widget: list
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: Description, name: description, widget: string}
                  - {label: Items, name: items, widget: list, required: false}
                  - {label: Image, name: imageUrl, widget: image, required: false}
          - label: "Arguments for Pluralism"
            name: arguments
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - label: Tiles
                name: tiles
                widget: list
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: Text, name: text, widget: text}
                  - {label: Image, name: image, widget: image, required: false}
          - label: "Team"
            name: team
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: "Team Image", name: image, widget: image}
          - {label: "Details", name: details, widget: markdown, required: false}
          - label: Quotes
            name: quotes
            widget: list
            required: false
            fields:
              - {label: Quote, name: quote, widget: string}
              - {label: Author, name: author, widget: string}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Menu", name: "menu", widget: "hidden", default: "{main: {weight: -60}}"}
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/project/conference-2019.md"
        label: "PINE Conference 2019"
        name: "conference-2019"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "conference-2019"}
          - {label: "Menu", name: "menu", widget: "hidden", default: "{main: {weight: -100}}"}
          - {label: Title, name: title, widget: string}
          - {label: "Published", name: "publishdate", widget: "datetime"}
          - {label: "Last Updated", name: "lastmod", widget: "datetime"}
          - {label: Image, name: image, widget: image}
          - {label: Description, name: description, widget: string}
          - label: Intro
            name: intro
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: markdown}
              - {label: Image, name: imageUrl, widget: image}
              - {label: "Button Text", name: button, widget: string}
              - {label: "Button URL", name: link, widget: string}
          - {label: Details, name: details, widget: markdown, required: false}
          - label: Tracks
            name: tracks
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - label: Tiles
                name: tiles
                widget: list
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: Text, name: text, widget: text}
                  - {label: Image, name: image, widget: image, required: false}
          - label: Experts
            name: experts
            widget: object
            fields:
              - {label: "Heading", name: heading, widget: string}
              - {label: "Description", name: description, widget: string}
              - label: "Expert list"
                name: expert_list
                widget: list
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: Text, name: text, widget: text}
                  - {label: Image, name: imageUrl, widget: image}
          - label: Schedule
            name: schedule
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Content, name: content, widget: markdown}
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - label: Intro,
            name: intro,
            widget: object,
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - label: Tiles
                name: tiles
                widget: list
                fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
